create table if not exists public.settings(
 id bigint primary key,
 shop_name text not null default 'TON PRINTING',
 tagline text not null default 'งานพิมพ์และงานสื่อสิ่งพิมพ์ครบวงจร',
 footer text not null default '',
 logo text not null default '',
 phone text not null default '',
 line text not null default '',
 facebook text not null default '',
 email text not null default '',
 address text not null default '',
 qr_code text not null default ''
);
create table if not exists public.products(
 id bigint generated by default as identity primary key,
 category text not null,
 name text not null,
 price text not null default '',
 description text not null default '',
 image text not null default ''
);
alter table public.settings add column if not exists logo text not null default '';
alter table public.settings add column if not exists phone text not null default '';
alter table public.settings add column if not exists line text not null default '';
alter table public.settings add column if not exists facebook text not null default '';
alter table public.settings add column if not exists email text not null default '';
alter table public.settings add column if not exists address text not null default '';
alter table public.settings add column if not exists qr_code text not null default '';
insert into public.settings(id) values(1) on conflict(id) do nothing;
